server:
  port: 9909
spring:
  application:
    name: cy-sms #指定服务名
  rabbitmq:
    host: 127.0.0.1
aliyun:
  sms:
    accessKeyId: 1
    accessKeySecret: 2
    template_code: SMS_85735065
    sign_name: 黑马