server: 
  port: 9003
spring: 
  application:  
    name: cy-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cy_qa?characterEncoding=UTF8
    username: root
    password: 
  jpa: 
    database: MySQL
    show-sql: true
jwt:
  config:
    key: itcast
feign:
  hystrix:
    enabled: true
eureka:
  client:
    service‐url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer‐ip‐address: true