server: 
  port: 9004
spring: 
  application:  
    name: cy-article #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cy_article?characterEncoding=UTF8
    username: root
    password: 
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: