server:
  port: 9911
spring:
  application:
   name: cy-manager #指定服务名
eureka:
  client:
   serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
    defaultZone: http://127.0.0.1:6868/eureka/
   instance:
    prefer-ip-address: true
jwt:
  config:
   key: itcast
zuul:
  routes:
   cy-gathering: #活动
     path: /gathering/** #配置请求URL的请求规则
     serviceId: cy-gathering #指定Eureka注册中心中的服务id
   cy-article: #文章
     path: /article/** #配置请求URL的请求规则
     serviceId: cy-article #指定Eureka注册中心中的服务id
   cy-base: #基础
     path: /base/** #配置请求URL的请求规则
     serviceId: cy-base #指定Eureka注册中心中的服务id
   cy-qa: #问答
     path: /qa/** #配置请求URL的请求规则
     serviceId: cy-qa #指定Eureka注册中心中的服务id
   cy-recruit: #招聘
     path: /recruit/** #配置请求URL的请求规则
     serviceId: cy-recruit #指定Eureka注册中心中的服务id
   cy-user: #用户
     path: /user/** #配置请求URL的请求规则
     serviceId: cy-user #指定Eureka注册中心中的服务id