server: 
  port: 9908
spring: 
  application:  
    name: cy-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cy_user?characterEncoding=UTF8
    username: root
    password: 
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

jwt:
  config:
    key: itcast
    ttl: 360000
eureka:
  client:
    service‐url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer‐ip‐address: true
